### PR TITLE
refactor: add typescript types

### PR DESCRIPTION
**Pull request by adipasquale**
This PR adds TypeScript support by exporting types

It is based on previous work done on an external repo that only contained types: https://github.com/adipasquale/react-dsfr-types. 

- For each component there is a matching `[component].d.ts` file
- For each directory there is a `index.d.ts` that exports the nested types
- There is a root `index.d.ts` that exports all types

This structure is based on the [Typescript recommendations](https://www.typescriptlang.org/docs/handbook/declaration-files/templates/module-d-ts.html#library-file-layout) 

Types were auto-generated by translating the existing proptypes using [`react2dts`](https://github.com/KnisterPeter/react-to-typescript-definitions). 

⚠️ most types were auto-generated and were not used so far. The only usage was for a few components like Button, Tag, Container in the [enfants-du-spectacle repo](https://github.com/SocialGouv/enfants-du-spectacle/) 
⚠️ the react2dts failed for a single component so its type is missing, but I forgot to note which 🤦

### CODE REVIEW

**Comment by adipasquale** [comment]
I just figured out I missed a few steps with the rollup build and whatnot, so I don't think this PR is ready to be merged just yet. If anyone more experienced with publishing JS/TS packages cares to help, it'd be more than welcome :)

**Comment by adipasquale** [comment]
👋 hello, unfortunately I'm not going to be working anymore on the mission that made me open this PR. I'm going to leave this hanging 😢 sorry. I hope someone can take back ownership maybe @revolunet or @bertrandlalo ?

**Comment by revolunet** [comment]
Que dites-vous de finaliser et merger cette PR qui fournit déjà les definitions et n'impacte pas le code, puis migrer progressivement les composants en TS dans d'autres PR ?

**Comment by poplingue** [comment]
Pas d'impact de code mais ça va demander du temps pour faire fonctionner le build qui crash.

**Comment by revolunet** [comment]
Avec [quelques modifs](https://github.com/adipasquale/react-dsfr/pull/1) ca semble fonctionnel chez moi, mais je ne suis pas un expert TS; @desoindx a peut être de meilleures idées

**Comment by maxgfr** [comment]
+1

**Comment by revolunet** [comment]
à jour ici : #225

**Pull request closed without merging**
